#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${APS_ROOT_DIR:-$HOME/autoware.APS}"
HMI_TEST_ROOT="${APS_HMI_TEST_ROOT:-$HOME/hmi_test}"
SETUP_ENV_CACHE="${APS_HMI_SETUP_ENV_CACHE:-$HMI_TEST_ROOT/.cache/autoware_setup_env.bash}"

if [[ ! -f /opt/ros/humble/setup.bash ]]; then
  echo "[ERROR] missing ROS setup: /opt/ros/humble/setup.bash" >&2
  exit 1
fi

if [[ ! -f "${ROOT_DIR}/install/setup.bash" ]]; then
  echo "[ERROR] missing workspace setup: ${ROOT_DIR}/install/setup.bash" >&2
  exit 1
fi

mkdir -p "$(dirname "${SETUP_ENV_CACHE}")"
tmp="$(mktemp "${SETUP_ENV_CACHE}.tmp.XXXXXX")"
trap 'rm -f "${tmp}"' EXIT

{
  echo "# Generated by scripts/generate_autoware_setup_env_cache.sh"
  echo "# Regenerate after rebuilding or replacing ${ROOT_DIR}/install."
  echo "# Generated at $(date --iso-8601=seconds)"
  export PATH="${APS_HMI_BASE_PATH:-$HOME/.local/bin:$HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin}"
  set +u
  # shellcheck disable=SC1091
  source /opt/ros/humble/setup.bash
  # shellcheck disable=SC1091
  source "${ROOT_DIR}/install/setup.bash"
  set -u

  for key in \
    AMENT_PREFIX_PATH \
    CMAKE_PREFIX_PATH \
    COLCON_PREFIX_PATH \
    LD_LIBRARY_PATH \
    PATH \
    PYTHONPATH \
    ROS_DISTRO \
    ROS_LOCALHOST_ONLY \
    ROS_PYTHON_VERSION \
    ROS_VERSION; do
    if [[ -v "${key}" ]]; then
      printf 'export %s=%q\n' "${key}" "${!key}"
    fi
  done
} > "${tmp}"

mv "${tmp}" "${SETUP_ENV_CACHE}"
trap - EXIT
echo "[INFO] wrote ${SETUP_ENV_CACHE}"
