#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${APS_ROOT_DIR:-$HOME/autoware.APS}"
HMI_TEST_ROOT="${HMI_TEST_ROOT:-$HOME/hmi_test}"

export APS_ROOT_DIR="${ROOT_DIR}"
export HMI_TEST_ROOT="${HMI_TEST_ROOT}"
export APS_HMI_TEST_ROOT="${APS_HMI_TEST_ROOT:-$HMI_TEST_ROOT}"
export APS_HMI_PID_DIR="${APS_HMI_PID_DIR:-$HMI_TEST_ROOT/.pid}"
export APS_HMI_LOG_DIR="${APS_HMI_LOG_DIR:-$HMI_TEST_ROOT/.log}"
export APS_HMI_ROS_DIR="${APS_HMI_ROS_DIR:-$HMI_TEST_ROOT/.ros}"
export APS_HMI_WEBENGINE_CACHE_DIR="${APS_HMI_WEBENGINE_CACHE_DIR:-$HMI_TEST_ROOT/.cache/webengine}"
export APS_LOCAL_STACK_PID_DIR="${APS_LOCAL_STACK_PID_DIR:-$APS_HMI_PID_DIR}"
export APS_LOCAL_STACK_LOG_DIR="${APS_LOCAL_STACK_LOG_DIR:-$APS_HMI_LOG_DIR}"
export APS_FB_RUNTIME_ROOT="${APS_FB_RUNTIME_ROOT:-$HMI_TEST_ROOT}"
export APS_FB_PID_DIR="${APS_FB_PID_DIR:-$APS_HMI_PID_DIR}"
export APS_FB_LOG_DIR="${APS_FB_LOG_DIR:-$APS_HMI_LOG_DIR}"
export APS_FB_ROS_DIR="${APS_FB_ROS_DIR:-$APS_HMI_ROS_DIR}"
export APS_HMI_SCRIPT_DIR="${APS_HMI_SCRIPT_DIR:-$ROOT_DIR/scripts}"

mkdir -p \
  "${APS_HMI_PID_DIR}" \
  "${APS_HMI_LOG_DIR}" \
  "${APS_HMI_ROS_DIR}" \
  "${APS_HMI_ROS_DIR}/log" \
  "${APS_HMI_WEBENGINE_CACHE_DIR}"
